<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>0.2.0-preview.4</Version>
    <Copyright>Copyright (C) 2026 bluecutt</Copyright>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
