<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><AssemblyName>ComicEditor</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../ComicEditor.Rendering/ComicEditor.Rendering.csproj" /><ProjectReference Include="../ComicEditor.Session/ComicEditor.Session.csproj"/></ItemGroup></Project>
