using System.Drawing;
using System.Text.Json.Nodes;
using ComicEditor.Rendering;
namespace ComicEditor.Tests;
public sealed class BalloonBorderCases : ITestSuite
{
    public IEnumerable<TestCase> Cases()
    {
        foreach(var scale in new[]{1,2,2.5}) yield return new("BalloonBorder.FullTopAndLeft."+scale,()=>{
            var doc=BorderScenes.Scene(BorderScenes.Panel("A","[[20,20],[140,20],[140,120],[20,120]]")); using var before=new PageRenderer().RenderBitmap(doc,new(scale)); doc.Root["balloons"]!.AsArray().Add(BorderScenes.Balloon("B","A")); using var after=new PageRenderer().RenderBitmap(doc,new(scale)); BorderScenes.StripSame(before.Pixels,after.Pixels,(int)(35*scale),(int)(16*scale),(int)(50*scale),(int)(23*scale)); BorderScenes.StripSame(before.Pixels,after.Pixels,(int)(16*scale),(int)(35*scale),(int)(23*scale),(int)(50*scale)); Assert.True(after.Pixels.GetPixel((int)(40*scale),(int)(40*scale)).R>245);
        });
        yield return new("BalloonBorder.NeighborOwnsDivider",()=>{ var doc=BorderScenes.Scene(BorderScenes.Panel("A","[[20,20],[140,20],[140,70],[20,70]]",10),BorderScenes.Panel("B","[[20,70],[140,70],[140,120],[20,120]]",20)); using var before=new PageRenderer().RenderBitmap(doc,new()); var balloon=BorderScenes.Balloon("C","A"); balloon["transform"]!["x"]=40; balloon["transform"]!["y"]=50; balloon["transform"]!["width"]=40; balloon["transform"]!["height"]=40; doc.Root["balloons"]!.AsArray().Add(balloon); using var after=new PageRenderer().RenderBitmap(doc,new()); BorderScenes.StripSame(before.Pixels,after.Pixels,50,66,65,73); });
        yield return new("BalloonBorder.HiddenEdgeNoGhostGap",()=>{ var p=BorderScenes.Panel("A","[[20,20],[140,20],[140,120],[20,120]]"); p["edgeVisibility"]=JsonNode.Parse("[false,true,true,true]"); var doc=BorderScenes.Scene(p); doc.Root["balloons"]!.AsArray().Add(BorderScenes.Balloon("B","A")); using var page=new PageRenderer().RenderBitmap(doc,new()); Assert.True(page.Pixels.GetPixel(40,22).R>245); });
        yield return new("BalloonBorder.FreeCanCoverDivider",()=>{ var doc=BorderScenes.Scene(BorderScenes.Panel("A","[[20,20],[140,20],[140,120],[20,120]]")); doc.Root["balloons"]!.AsArray().Add(BorderScenes.Balloon("B","")); using var page=new PageRenderer().RenderBitmap(doc,new()); Assert.True(page.Pixels.GetPixel(40,20).R>245); });
        yield return new("BalloonBorder.MixedZPreserved",()=>{ var doc=BorderScenes.Scene(BorderScenes.Panel("A","[[20,20],[140,20],[140,120],[20,120]]")); doc.Root["balloons"]!.AsArray().Add(BorderScenes.Balloon("clipped","A","white",20)); doc.Root["balloons"]!.AsArray().Add(BorderScenes.Balloon("free","","blue",10)); using var page=new PageRenderer().RenderBitmap(doc,new()); Assert.True(page.Pixels.GetPixel(40,40).R>245); Assert.Equal(Color.Blue.ToArgb(),page.Pixels.GetPixel(40,20).ToArgb()); });
        foreach(var opaque in new[]{false,true}) yield return new("BalloonBorder.InsetAlpha."+opaque,()=>{ var front=BorderScenes.Panel("Inset","[[40,10],[80,10],[80,45],[40,45]]",20,opaque?"gray":"transparent"); front["clearFrame"]=false; var doc=BorderScenes.Scene(BorderScenes.Panel("A","[[20,20],[140,20],[140,120],[20,120]]",10),front); using var before=new PageRenderer().RenderBitmap(doc,new()); doc.Root["balloons"]!.AsArray().Add(BorderScenes.Balloon("B","A")); using var after=new PageRenderer().RenderBitmap(doc,new()); if(!opaque) BorderScenes.StripSame(before.Pixels,after.Pixels,50,16,60,23); else Assert.True(after.Pixels.GetPixel(55,20).R>245,"Phantom stroke gap in opaque inset"); });
        foreach(var scale in new[]{1,2,2.5}) yield return new("BalloonBorder.RotatedFlippedDiagonal."+scale,()=>{ var front=BorderScenes.Panel("Inset","[[40,70],[80,70],[80,115],[40,115]]",20,"transparent"); front["clearFrame"]=false; var doc=BorderScenes.Scene(BorderScenes.Panel("A","[[20,20],[130,20],[130,120],[20,80]]"),front); using var before=new PageRenderer().RenderBitmap(doc,new(scale)); var b=BorderScenes.Balloon("B","A"); b["transform"]!["x"]=45; b["transform"]!["y"]=65; b["transform"]!["width"]=50; b["transform"]!["height"]=60; b["transform"]!["rotation"]=30; b["transform"]!["flipX"]=true; doc.Root["balloons"]!.AsArray().Add(b); using var after=new PageRenderer().RenderBitmap(doc,new(scale)); for(var x=55;x<=85;x++) { var edgeY=80+(x-20)*40d/110; BorderScenes.StripSame(before.Pixels,after.Pixels,(int)(x*scale),(int)Math.Floor((edgeY-4)*scale),(int)(x*scale),(int)Math.Ceiling((edgeY+4)*scale)); } });
    }
}
