using System.Drawing;
using ComicEditor.Core.Assets;
using ComicEditor.Core.Project;
using ComicEditor.Core.Validation;
using ComicEditor.Rendering;
namespace ComicEditor.Tests;
public sealed class BundleCases : ITestSuite
{
    public IEnumerable<TestCase> Cases()=>[
        new("Bundle.SameNameDifferentContent",()=>{ var d=CommandCases.Scene(); var dir=Path.GetDirectoryName(d.SourcePath)!; Directory.CreateDirectory(Path.Combine(dir,"other")); using(var b=new Bitmap(20,20)) { using(var g=Graphics.FromImage(b))g.Clear(Color.Green); b.Save(Path.Combine(dir,"other/art.png")); } d.Root["panels"]![1]!["sourceImage"]="other/art.png"; var source=new ProjectStore().Save(d,Path.Combine(dir,"project.json"),new()); var bundle=ProjectBundler.Bundle(source,Path.Combine(dir,"bundle")); var assets=new AssetResolver().Inspect(bundle.Document); Assert.True(assets.All(a=>a.Error is null)); Assert.True(assets[0].Reference!=assets[1].Reference); Assert.True(assets.All(a=>!Path.IsPathRooted(a.Reference))); Assert.Equal(source.Sha256,AtomicFile.Hash(source.AbsolutePath)); }),
        new("Bundle.MovedFolderStillRenders",()=>{ var d=CommandCases.Scene(); var dir=Path.GetDirectoryName(d.SourcePath)!; var source=new ProjectStore().Save(d,Path.Combine(dir,"project.json"),new()); var bundle=ProjectBundler.Bundle(source,Path.Combine(dir,"bundle")); var moved=Path.Combine(dir,"搬迁 空格"); Directory.Move(Path.GetDirectoryName(bundle.AbsolutePath)!,moved); var relocated=new ProjectStore().Load(Path.Combine(moved,"project.json")); using var before=new PageRenderer().RenderBitmap(source.Document,new(1)); using var after=new PageRenderer().RenderBitmap(relocated.Document,new(1)); Assert.Equal(0,Pixels.Differences(before.Pixels,after.Pixels)); }),
        new("Bundle.TraversalRejected",()=>{ Assert.Throws<EditorException>(()=>ProjectBundler.PackagePath(TestFiles.Directory(),"../escape.png")); Assert.Throws<EditorException>(()=>ProjectBundler.PackagePath(TestFiles.Directory(),"C:/outside.png")); }),
        new("Bundle.MissingAndExistingNoOverwrite",()=>{ var d=CommandCases.Scene(); var dir=Path.GetDirectoryName(d.SourcePath)!; d.Root["panels"]![0]!["sourceImage"]="missing.png"; var source=new ProjectStore().Save(d,Path.Combine(dir,"project.json"),new()); var output=Path.Combine(dir,"bundle"); Assert.Throws<EditorException>(()=>ProjectBundler.Bundle(source,output)); Assert.True(!Directory.Exists(output)); Directory.CreateDirectory(output); File.WriteAllText(Path.Combine(output,"keep.txt"),"keep"); Assert.Throws<EditorException>(()=>ProjectBundler.Bundle(source,output)); Assert.Equal("keep",File.ReadAllText(Path.Combine(output,"keep.txt"))); }),
        new("Bundle.CancelAndReadOnlySource",()=>{ var d=CommandCases.Scene(); var dir=Path.GetDirectoryName(d.SourcePath)!; var source=new ProjectStore().Save(d,Path.Combine(dir,"project.json"),new()); var asset=ProjectPaths.Resolve(d,"art.png"); File.SetAttributes(asset,File.GetAttributes(asset)|FileAttributes.ReadOnly); try { var b=ProjectBundler.Bundle(source,Path.Combine(dir,"bundle")); Assert.True(File.Exists(b.AbsolutePath)); using var c=new CancellationTokenSource(); c.Cancel(); Assert.Throws<OperationCanceledException>(()=>ProjectBundler.Bundle(source,Path.Combine(dir,"cancel"),c.Token)); Assert.True(!Directory.Exists(Path.Combine(dir,"cancel"))); } finally { File.SetAttributes(asset,FileAttributes.Normal); } })
    ];
}
