using System.Diagnostics;
using System.Text;
using System.Text.Json.Nodes;
using ComicEditor.Core.Project;
namespace ComicEditor.Tests;
public sealed class CliCases : ITestSuite
{
    public static (int Exit,JsonObject Envelope) Run(params string[] args)
    {
        var path=Path.GetFullPath("src/ComicEditor.Cli/bin/Debug/net10.0-windows/ComicEditor.Cli.exe");
        var start=new ProcessStartInfo(path) { UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8 };
        start.Environment["DOTNET_ROOT"]=Path.GetFullPath(".tools/dotnet"); foreach(var arg in args) start.ArgumentList.Add(arg);
        using var process=Process.Start(start)!; var errorTask=process.StandardError.ReadToEndAsync(); var stdout=process.StandardOutput.ReadToEnd();
        Assert.True(process.WaitForExit(45000),"CLI subprocess timed out"); var error=errorTask.GetAwaiter().GetResult();
        JsonObject output; try { output=JsonNode.Parse(stdout)!.AsObject(); } catch(Exception ex) { throw new Exception("CLI stdout not one JSON envelope: "+stdout+" "+error,ex); }
        foreach(var key in new[]{"apiVersion","requestId","success","code","message","data","changedObjects","warnings"}) Assert.True(output.ContainsKey(key),"Missing envelope key "+key);
        return(process.ExitCode,output);
    }
    public static (LoadedProject Project,string Patch,string Out) Patch()
    {
        var doc=CommandCases.Scene(); var dir=Path.GetDirectoryName(doc.SourcePath)!; var project=new ProjectStore().Save(doc,Path.Combine(dir,"source.json"),new());
        var patch=new JsonObject { ["apiVersion"]=1,["requestId"]=Guid.NewGuid().ToString(),["baseProjectHash"]=project.Sha256,["operations"]=JsonNode.Parse("""[{"op":"balloon.move","targetId":"X","args":{"dx":4,"dy":5}}]""") };
        var path=Path.Combine(dir,"patch.json"); File.WriteAllText(path,patch.ToJsonString()); return(project,path,Path.Combine(dir,"after.json"));
    }
    public IEnumerable<TestCase> Cases()=>[
        new("Cli.JsonOnlyStdout",()=>{ var r=Run("capabilities"); Assert.Equal(0,r.Exit); Assert.True(r.Envelope.Flag("success")); Assert.Equal(1d,r.Envelope.Number("apiVersion")); }),
        new("Cli.InitApplyRender",()=>{ var initial=Patch(); var manifest=new JsonObject{["apiVersion"]=1,["project"]=initial.Project.Document.Root.DeepClone(),["assetMap"]=new JsonArray()}; var path=Path.Combine(Path.GetDirectoryName(initial.Project.AbsolutePath)!,"manifest.json"); File.WriteAllText(path,manifest.ToJsonString()); var initialized=Path.Combine(Path.GetDirectoryName(path)!,"initialized.json"); Assert.Equal(0,Run("init","--manifest",path,"--out",initialized).Exit); Assert.Equal(0,Run("inspect","--project",initialized).Exit); Assert.Equal(0,Run("apply","--project",initial.Project.AbsolutePath,"--patch",initial.Patch,"--out",initial.Out).Exit); Assert.Equal(0,Run("validate","--project",initial.Out).Exit); var png=Path.Combine(Path.GetDirectoryName(path)!,"render.png"); var rendered=Run("render","--project",initial.Out,"--out",png,"--scale","2.5"); Assert.Equal(0,rendered.Exit); Assert.Equal(400d,rendered.Envelope["data"].Number("width")); Assert.Equal(350d,rendered.Envelope["data"].Number("height")); Assert.Equal(initial.Project.Sha256,AtomicFile.Hash(initial.Project.AbsolutePath)); }),
        new("Cli.DryRunNoWrites",()=>{ var data=Patch(); var r=Run("apply","--project",data.Project.AbsolutePath,"--patch",data.Patch,"--out",data.Out,"--dry-run"); Assert.Equal(0,r.Exit); Assert.True(!File.Exists(data.Out)); Assert.True(r.Envelope["changedObjects"]!.AsArray().Count>0); Assert.Equal(data.Project.Sha256,AtomicFile.Hash(data.Project.AbsolutePath)); }),
        new("Cli.ConflictNoWrites",()=>{ var data=Patch(); File.AppendAllText(data.Project.AbsolutePath," "); var hash=AtomicFile.Hash(data.Project.AbsolutePath); Assert.Equal(4,Run("apply","--project",data.Project.AbsolutePath,"--patch",data.Patch,"--out",data.Out).Exit); Assert.True(!File.Exists(data.Out)); Assert.Equal(hash,AtomicFile.Hash(data.Project.AbsolutePath)); }),
        new("Cli.UnknownArgsAndMissingAsset",()=>{ Assert.Equal(2,Run("capabilities","--unknown").Exit); var data=Patch(); var doc=data.Project.Document; doc.Root["panels"]![0]!["sourceImage"]="missing.png"; var path=Path.Combine(Path.GetDirectoryName(data.Out)!,"missing.json"); new ProjectStore().Save(doc,path,new()); Assert.Equal(3,Run("render","--project",path,"--out",data.Out+".png").Exit); }),
        new("Cli.LockedBatchRejected",()=>{ var data=Patch(); var doc=data.Project.Document.DeepClone(); doc.Root["balloons"]![0]!["locked"]=true; var saved=new ProjectStore().Save(doc,Path.Combine(Path.GetDirectoryName(data.Out)!,"locked.json"),new()); var patch=JsonNode.Parse(File.ReadAllText(data.Patch))!.AsObject(); patch["baseProjectHash"]=saved.Sha256; File.WriteAllText(data.Patch,patch.ToJsonString()); Assert.Equal(5,Run("apply","--project",saved.AbsolutePath,"--patch",data.Patch,"--out",data.Out).Exit); Assert.True(!File.Exists(data.Out)); }),
        new("Cli.RenderOverwriteRequiresOutputHash",()=>{ var data=Patch(); var png=data.Out+".png"; File.WriteAllText(png,"unchanged"); Assert.Equal(4,Run("render","--project",data.Project.AbsolutePath,"--out",png,"--overwrite").Exit); Assert.Equal("unchanged",File.ReadAllText(png)); Assert.Equal(0,Run("render","--project",data.Project.AbsolutePath,"--out",png,"--overwrite","--if-output-hash",AtomicFile.Hash(png)).Exit); }),
        new("Cli.ReportCollisionNoWrites",()=>{ var d=Patch(); Assert.Equal(2,Run("apply","--project",d.Project.AbsolutePath,"--patch",d.Patch,"--out",d.Out,"--report",d.Out).Exit); Assert.True(!File.Exists(d.Out)); }),
        new("Cli.ReportFailurePreservesReceipt",()=>{ var d=Patch(); var report=Path.Combine(Path.GetDirectoryName(d.Out)!,"report.json"); var dispatcher=new ComicEditor.Cli.CliDispatcher(()=>File.WriteAllText(report,"raced")); var r=dispatcher.RunAsync(["apply","--project",d.Project.AbsolutePath,"--patch",d.Patch,"--out",d.Out,"--report",report]).GetAwaiter().GetResult(); Assert.Equal(0,r.ExitCode); Assert.True(r.Envelope.Flag("success")); Assert.True(File.Exists(d.Out)); Assert.True(r.Envelope["warnings"]!.AsArray().Count>0); Assert.Equal("raced",File.ReadAllText(report)); }),
        new("Cli.CancelTimeoutInternalCodes",()=>{ using var c=new CancellationTokenSource(); c.Cancel(); Assert.Equal(6,new ComicEditor.Cli.CliDispatcher().RunAsync(["capabilities"],c.Token).GetAwaiter().GetResult().ExitCode); Assert.Equal(6,new ComicEditor.Cli.CliDispatcher(()=>Thread.Sleep(40)).RunAsync(["capabilities","--timeout","0.001"]).GetAwaiter().GetResult().ExitCode); Assert.Equal(70,new ComicEditor.Cli.CliDispatcher(()=>throw new Exception("test fault")).RunAsync(["capabilities"]).GetAwaiter().GetResult().ExitCode); }),
        new("Cli.PatchLimits",()=>{ var d=Patch(); var root=JsonNode.Parse(File.ReadAllText(d.Patch))!.AsObject(); var ops=root["operations"]!.AsArray(); for(var n=1;n<1001;n++) ops.Add(ops[0]!.DeepClone()); File.WriteAllText(d.Patch,root.ToJsonString()); Assert.Equal(2,Run("apply","--project",d.Project.AbsolutePath,"--patch",d.Patch,"--out",d.Out).Exit); File.WriteAllText(d.Patch,new string(' ',8*1024*1024+1)); Assert.Equal(2,Run("apply","--project",d.Project.AbsolutePath,"--patch",d.Patch,"--out",d.Out).Exit); Assert.True(!File.Exists(d.Out)); }),
        new("Cli.RetryDoesNotMoveTwice",()=>{ var d=Patch(); Assert.Equal(0,Run("apply","--project",d.Project.AbsolutePath,"--patch",d.Patch,"--out",d.Project.AbsolutePath,"--overwrite","--if-output-hash",d.Project.Sha256).Exit); var hash=AtomicFile.Hash(d.Project.AbsolutePath); Assert.Equal(4,Run("apply","--project",d.Project.AbsolutePath,"--patch",d.Patch,"--out",d.Project.AbsolutePath,"--overwrite","--if-output-hash",hash).Exit); Assert.Equal(hash,AtomicFile.Hash(d.Project.AbsolutePath)); }),
        new("Cli.P10OnlyOneBalloon",()=>{ var original=new ProjectStore().Load("artifacts/private-fixtures/P10SingleLine.json"); var dir=TestFiles.Directory(); var manifest=Path.Combine(dir,"manifest.json"); File.WriteAllText(manifest,new JsonObject{["apiVersion"]=1,["project"]=original.Document.Root.DeepClone(),["assetMap"]=new JsonArray()}.ToJsonString()); var source=Path.Combine(dir,"source.json"); Assert.Equal(0,Run("init","--manifest",manifest,"--out",source).Exit); var inspected=Run("inspect","--project",source); Assert.Equal(0,inspected.Exit); var doc=inspected.Envelope["data"]!["project"]!.AsObject(); var id=doc["balloons"]![0].Text("id"); var patch=Path.Combine(dir,"patch.json"); File.WriteAllText(patch,new JsonObject{["apiVersion"]=1,["requestId"]=Guid.NewGuid().ToString(),["baseProjectHash"]=AtomicFile.Hash(source),["operations"]=new JsonArray(new JsonObject{["op"]="balloon.move",["targetId"]=id,["args"]=new JsonObject{["dx"]=2,["dy"]=1}})}.ToJsonString()); var output=Path.Combine(dir,"after.json"); Assert.Equal(0,Run("apply","--project",source,"--patch",patch,"--out",output).Exit); var after=new ProjectStore().Load(output).Document.Root; Assert.True(JsonNode.DeepEquals(doc["panels"],after["panels"])); for(var i=1;i<doc["balloons"]!.AsArray().Count;i++) Assert.True(JsonNode.DeepEquals(doc["balloons"]![i],after["balloons"]![i])); Assert.Equal(0,Run("validate","--project",output).Exit); Assert.Equal(0,Run("render","--project",output,"--out",Path.Combine(dir,"page.png")).Exit); Assert.Equal(original.Sha256,AtomicFile.Hash(original.AbsolutePath)); })
    ];
}
