using System.Text.Json.Nodes;
using ComicEditor.Core.Project;
using ComicEditor.Core.Commands;
using ComicEditor.Rendering;
using ComicEditor.Session;
namespace ComicEditor.Tests;
public sealed class ReviewCases : ITestSuite
{
    public IEnumerable<TestCase> Cases()=>[
        new("Review.InitFreezesBaseAndReset",()=>{var initialized=ProjectInitializer.Create(SkillCases.Folder+"/assets/init-manifest-example.json");var before=new ProjectView(initialized).Panels.First();var rect=DrawingGeometry.ImageRect(before,800,600);var moved=new CommandProcessor().Plan(initialized,[new("panel.move","P01",new(){["dx"]=10,["dy"]=0,["moveImage"]=true})]).After;Assert.Equal(10f,DrawingGeometry.ImageRect(new ProjectView(moved).Panels.First(),800,600).X-rect.X);var reset=new CommandProcessor().Plan(moved,[new("object.reset","P01",new(){["kind"]="panel",["scope"]="frame"}),new("object.reset","P01",new(){["kind"]="panel",["scope"]="image"})]).After;Assert.True(JsonNode.DeepEquals(before["polygon"],reset.Root["panels"]![0]!["polygon"]));var b0=initialized.Root["balloons"]![0]!["transform"]!.DeepClone();var movedBalloon=new CommandProcessor().Plan(initialized,[new("balloon.move","B01",new(){["dx"]=10,["dy"]=5}),new("object.reset","B01",new(){["kind"]="balloon",["scope"]="balloon"})]).After;Assert.True(JsonNode.DeepEquals(b0,movedBalloon.Root["balloons"]![0]!["transform"]));}),
        new("Review.RawLoadRoundtripAndFirstEditAnchor",()=>{var doc=CommandCases.Scene();var panel=doc.Root["panels"]![0]!.AsObject();panel.Remove("initialPolygon");panel.Remove("initialImageTransform");var path=Path.Combine(TestFiles.Directory(),"raw.json");var saved=new ProjectStore().Save(doc,path,new());Assert.True(!saved.Document.Root["panels"]![0]!.AsObject().ContainsKey("initialPolygon"));var before=DrawingGeometry.ImageRect(saved.Document.Root["panels"]![0]!.AsObject(),20,20);var moved=new CommandProcessor().Plan(saved.Document,[new("panel.move","A",new(){["dx"]=10,["dy"]=0})]).After;Assert.Equal(10f,DrawingGeometry.ImageRect(moved.Root["panels"]![0]!.AsObject(),20,20).X-before.X);}),
        new("Review.MissingSourceRelink",()=>{foreach(var policy in new[]{"preserve","refit"}){var doc=CommandCases.Scene();doc.Root["panels"]![0]!["sourceImage"]="missing.png";var plan=new CommandProcessor().Plan(doc,[new("asset.replace","A",new(){["kind"]="panel",["sourceImage"]="art.png",["fitPolicy"]=policy})]);Assert.Equal("art.png",plan.After.Root["panels"]![0].Text("sourceImage"));Assert.True(plan.Warnings.Any(i=>i.Code=="ASSET_RELINK"));Assert.True(JsonNode.DeepEquals(doc.Root["panels"]![1],plan.After.Root["panels"]![1]));}}),
        new("Review.SessionSaveCallerRelativePath",()=>{var dir=TestFiles.Directory();var registry=Path.Combine(dir,"registry");var editor=new FakeEditorSession{AllowWrite=true};using var host=new SessionHost(editor,registry);var relative=Path.GetRelativePath(Environment.CurrentDirectory,Path.Combine(dir,"中文 Agent 保存.json"));var args=ComicEditor.Cli.CliParser.Parse(["session","save","--session",host.Id,"--registry-dir",registry,"--revision","0","--base-hash",SessionHash.Compute(editor.Snapshot()),"--out",relative]);var result=ComicEditor.Cli.SessionCommands.Execute(args,Guid.NewGuid().ToString(),CancellationToken.None);Assert.Equal(0,result.ExitCode);Assert.Equal(Path.GetFullPath(relative),editor.LastSavePath);}),
        new("Review.HelpSelfDiscovery",()=>{var result=CliCases.Run("--help");Assert.Equal(0,result.Exit);Assert.True(result.Envelope["data"]!.ToJsonString().Contains("--manifest"));Assert.Equal(0,CliCases.Run("render","--help").Exit);}),
        new("Review.ReadingOrderEditable",()=>{var doc=CommandCases.Scene();var result=new CommandProcessor().Plan(doc,[new("object.layer","A",new(){["kind"]="panel",["readingOrder"]=4})]);Assert.Equal(4d,result.After.Root["panels"]![0].Number("readingOrder"));Assert.True(JsonNode.DeepEquals(doc.Root["balloons"],result.After.Root["balloons"]));})
    ];
}
