using System.Text.Json.Nodes;
using ComicEditor.Core.Project;
namespace ComicEditor.Tests;
public sealed class SkillCases : ITestSuite
{
    public const string Folder="skills/comic-page-workflow";
    public IEnumerable<TestCase> Cases()=>[
        new("Skill.ExamplesValidateAgainstSchema",()=>{var manifest=Path.Combine(Folder,"assets/init-manifest-example.json");Assert.True(File.Exists(manifest));var output=Path.Combine(TestFiles.Directory(),"working.json");Assert.Equal(0,CliCases.Run("init","--manifest",manifest,"--out",output).Exit);Assert.Equal(0,CliCases.Run("validate","--project",output).Exit);var result=CliCases.Run("render","--project",output,"--out",output+".png","--scale","2.5");Assert.Equal(0,result.Exit);Assert.Equal(1600d,result.Envelope["data"].Number("width"));Assert.Equal(2250d,result.Envelope["data"].Number("height"));}),
        new("Skill.ReplacementChangesOnlyTarget",()=>{var dir=TestFiles.Directory();var file=Path.Combine(dir,"before.json");Assert.Equal(0,CliCases.Run("init","--manifest",Path.Combine(Folder,"assets/init-manifest-example.json"),"--out",file).Exit);var before=new ProjectStore().Load(file);var template=JsonNode.Parse(File.ReadAllText(Path.Combine(Folder,"assets/patch-example.json")))!.AsObject();template["requestId"]=Guid.NewGuid().ToString();template["baseProjectHash"]=before.Sha256;var replacement=Path.Combine(dir,"replacement.png");File.Copy("examples/minimal-page/balloon.png",replacement);template["operations"]![0]!["args"]!["sourceImage"]=replacement;var patch=Path.Combine(dir,"patch.json");File.WriteAllText(patch,template.ToJsonString());var output=Path.Combine(dir,"after.json");var result=CliCases.Run("apply","--project",file,"--patch",patch,"--out",output);Assert.Equal(0,result.Exit);var after=new ProjectStore().Load(output).Document;Assert.True(JsonNode.DeepEquals(before.Document.Root["panels"],after.Root["panels"]));var expected=before.Document.Root.DeepClone();expected["balloons"]![0]!["sourceImage"]=replacement;expected["assetBase"]=after.Root["assetBase"]!.DeepClone();Assert.True(JsonNode.DeepEquals(expected,after.Root),"Only selected source reference and save-as base may change");Assert.Equal(before.Sha256,AtomicFile.Hash(file));Assert.Equal(0,CliCases.Run("render","--project",output,"--out",output+".png").Exit);}),
        new("Skill.NoPersonalPathDependency",()=>{Assert.True(File.Exists(Path.Combine(Folder,"SKILL.md")));var r=PackageCases.Script("scripts/Scan-Public-Package.ps1","-Directory",Path.GetFullPath(Folder));Assert.Equal(0,r.Exit);var config=JsonNode.Parse(File.ReadAllText(Path.Combine(Folder,"assets/project-config-example.json")))!;Assert.True(!Path.IsPathRooted(config["editorCliPath"]!.GetValue<string>()));})
    ];
}
