using ComicEditor.Tests;
using ComicEditor.Desktop.ViewModels;
using ComicEditor.Desktop.Canvas;
using ComicEditor.Core.Project;
namespace ComicEditor.UiTests;
public sealed class DocumentLifecycleCases : ITestSuite
{
    public IEnumerable<TestCase> Cases()=>[
        new("UiLifecycle.DirtyOpenCancelPreservesState",()=>{var vm=new EditorViewModel(CommandCases.Scene());vm.Execute([CommandCases.Op("balloon.move","X","{\"dx\":3,\"dy\":4}")]);var before=vm.Document.Root.ToJsonString();var other=CommandCases.Scene();var saved=new ProjectStore().Save(other,Path.Combine(Path.GetDirectoryName(other.SourcePath)!,"other.json"),new());Assert.True(!vm.TryOpen(saved.AbsolutePath,()=>false));Assert.Equal(before,vm.Document.Root.ToJsonString());Assert.True(vm.TryOpen(saved.AbsolutePath,()=>true));}),
        new("UiLifecycle.OldPreviewCannotReplaceNewFrame",()=>{var old=new TaskCompletionSource<int>();var recent=new TaskCompletionSource<int>();var published=0;using var coordinator=new PreviewCoordinator<int>();var first=coordinator.RequestAsync(1,_=>old.Task,n=>published=n);var second=coordinator.RequestAsync(2,_=>recent.Task,n=>published=n);recent.SetResult(2);second.GetAwaiter().GetResult();old.SetResult(1);first.GetAwaiter().GetResult();Assert.Equal(2,published);}),
        new("UiLifecycle.SaveAsUndoResolvesSameAssets",()=>{var doc=CommandCases.Scene();var vm=new EditorViewModel(doc);vm.Execute([CommandCases.Op("balloon.move","X","{\"dx\":3,\"dy\":4}")]);var dir=Path.Combine(TestFiles.Directory(),"中文 子目录");Directory.CreateDirectory(dir);var saved=vm.Save(Path.Combine(dir,"new.json"),new());Assert.True(!vm.Dirty);var before=new ComicEditor.Core.Assets.AssetResolver().Inspect(vm.Document);vm.Undo();var after=new ComicEditor.Core.Assets.AssetResolver().Inspect(vm.Document);Assert.True(after.All(a=>a.Error is null));Assert.Equal(before[0].AbsolutePath,after[0].AbsolutePath);Assert.True(vm.Dirty);Assert.True(File.Exists(saved.AbsolutePath));}),
        new("UiLifecycle.P09P10ReopenRender",()=>{foreach(var name in new[]{"P09Legacy","P10SingleLine"}){var original=new ProjectStore().Load("artifacts/private-fixtures/"+name+".json");var vm=new EditorViewModel(original.Document);var path=Path.Combine(TestFiles.Directory(),"saved.json");vm.Save(path,new());var reopened=new EditorViewModel(CommandCases.Scene());reopened.Open(path);Assert.True(System.Text.Json.Nodes.JsonNode.DeepEquals(original.Document.Root["panels"],reopened.Document.Root["panels"]));Assert.True(System.Text.Json.Nodes.JsonNode.DeepEquals(original.Document.Root["balloons"],reopened.Document.Root["balloons"]));using var before=new ComicEditor.Rendering.PageRenderer().RenderBitmap(original.Document,new(2));using var after=new ComicEditor.Rendering.PageRenderer().RenderBitmap(reopened.Document,new(2));Assert.Equal(0,Pixels.Differences(before.Pixels,after.Pixels));Assert.Equal(original.Sha256,AtomicFile.Hash(original.AbsolutePath));}}),
        new("UiLifecycle.ExternalSaveConflict",()=>{var vm=new EditorViewModel(CommandCases.Scene());var saved=vm.Save(Path.Combine(TestFiles.Directory(),"saved.json"),new());File.AppendAllText(saved.AbsolutePath," ");Assert.Throws<ComicEditor.Core.Validation.EditorException>(()=>vm.Save(saved.AbsolutePath,new(true,vm.FileHash)));}),
        new("UiLifecycle.BackgroundExportCancellation",()=>{var vm=new EditorViewModel(CommandCases.Scene());using var token=new CancellationTokenSource();token.Cancel();var path=Path.Combine(TestFiles.Directory(),"cancel.png");Assert.Throws<OperationCanceledException>(()=>new ExportViewModel(vm).ExportAsync(path,new(2),token.Token).GetAwaiter().GetResult());Assert.True(!File.Exists(path)&&!vm.Busy);})
    ];
}
