using System.Windows.Controls;
using System.Windows.Input;
using ComicEditor.Tests;
using ComicEditor.Desktop.Canvas;
using ComicEditor.Desktop.Inspectors;
using ComicEditor.Desktop.ViewModels;
using ComicEditor.Core.Project;
namespace ComicEditor.UiTests;
public sealed class InputCases : ITestSuite
{
    public IEnumerable<TestCase> Cases()=>[
        new("UiInput.WheelOverFocusedNumberDoesNotEdit",()=>{ var vm=new EditorViewModel(CommandCases.Scene());vm.Select("balloon","X"); var before=vm.Document.Root.ToJsonString();var view=new InspectorView(vm,"balloon"); foreach(var key in new[]{"balloon.transform:width","balloon.transform:opacity","balloon.transform:lockAspect"}) { var control=view.Fields[key]; control.Focus();control.RaiseEvent(new MouseWheelEventArgs(Mouse.PrimaryDevice,Environment.TickCount,120){RoutedEvent=Mouse.PreviewMouseWheelEvent}); } Assert.Equal(before,vm.Document.Root.ToJsonString()); Assert.True(!vm.InputPending); }),
        new("UiInput.WheelCanvasChangesViewOnly",()=>{ var vm=new EditorViewModel(CommandCases.Scene());var before=vm.Document.Root.ToJsonString();var view=new ViewTransform();view.Wheel(120,new(50,50));Assert.True(view.Zoom>1);Assert.Equal(before,vm.Document.Root.ToJsonString()); }),
        new("UiInput.VertexWinsOverImage",()=>{var vm=new EditorViewModel(CommandCases.Scene());vm.Select("panel","A");var hit=HandleHitTest.Find(vm,EditMode.Vertex,new(20,20),8);Assert.True(hit?.DragKind==DragKind.Vertex);var router=new InputRouter(vm);router.Begin(hit!,new(20,20));router.Update(new(22,23));router.Commit();Assert.Equal(22d,vm.Document.Root["panels"]![0]!["polygon"]![0]![0]!.GetValue<double>());Assert.Equal(1d,vm.Document.Root["panels"]![0]!["imageTransform"].Number("offsetX")); }),
        new("UiInput.EscapeRestoresDrag",()=>{ var vm=new EditorViewModel(CommandCases.Scene());var before=vm.Document.Root.ToJsonString();var router=new InputRouter(vm);router.Begin(new("balloon","X",DragKind.Balloon),new(40,40));router.Update(new(55,60));Assert.True(router.Dragging&&router.Preview is not null);router.Cancel();Assert.Equal(before,vm.Document.Root.ToJsonString());Assert.True(!vm.Busy); }),
        new("UiInput.OneDragOneUndo",()=>{var vm=new EditorViewModel(CommandCases.Scene());var before=vm.Document.Root.ToJsonString();var router=new InputRouter(vm);router.Begin(new("balloon","X",DragKind.Balloon),new(40,40));router.Update(new(41,42));router.Update(new(45,49));router.Commit();Assert.Equal(35d,vm.Document.Root["balloons"]![0]!["transform"].Number("x"));vm.Undo();Assert.Equal(before,vm.Document.Root.ToJsonString());}),
        new("UiInput.LockedTargetCannotDrag",()=>{var d=CommandCases.Scene();d.Root["panels"]![0]!["locked"]=true;var vm=new EditorViewModel(d);var router=new InputRouter(vm);Assert.Throws<ComicEditor.Core.Validation.EditorException>(()=>router.Begin(new("panel","A",DragKind.Panel),new(20,20)));Assert.True(!vm.Busy);}),
        new("UiInput.SelectedTargetFixed",()=>{var vm=new EditorViewModel(CommandCases.Scene());var router=new InputRouter(vm);router.Begin(new("panel","A",DragKind.Panel),new(20,20));vm.Select("panel","B");router.Update(new(25,25));router.Commit();Assert.Equal(25d,vm.Document.Root["panels"]![0]!["polygon"]![0]![0]!.GetValue<double>());Assert.Equal(20d,vm.Document.Root["panels"]![1]!["polygon"]![0]![0]!.GetValue<double>());}),
        new("UiInput.CancelDoesNotUnlockUnrelatedBusy",()=>{var vm=new EditorViewModel(CommandCases.Scene()){Busy=true};new InputRouter(vm).Cancel();Assert.True(vm.Busy);}),
        new("UiInput.RealFocusedControlsWheelAndTextUndo",()=>{ var vm=new EditorViewModel(CommandCases.Scene());vm.Select("balloon","X");var inspector=new InspectorView(vm,"balloon");var window=new System.Windows.Window{Content=inspector,Width=370,Height=550};window.Show();window.UpdateLayout();try {var hash=vm.Document.Root.ToJsonString();foreach(var key in new[]{"balloon.transform:width","balloon.transform:opacity","balloon.transform:lockAspect"}) {var control=inspector.Fields[key];control.BringIntoView();window.UpdateLayout();control.Focus();Assert.True(control.IsKeyboardFocusWithin,"Actual control focus failed");control.RaiseEvent(new MouseWheelEventArgs(Mouse.PrimaryDevice,Environment.TickCount,-120){RoutedEvent=Mouse.PreviewMouseWheelEvent});Assert.Equal(hash,vm.Document.Root.ToJsonString());}var box=(TextBox)inspector.Fields["balloon.transform:width"];box.Focus();box.Text="45";box.Undo();Assert.Equal(hash,vm.Document.Root.ToJsonString());Assert.True(!FocusCommandPolicy.CanvasShortcutAllowed(box));Assert.True(!FocusCommandPolicy.CanvasShortcutAllowed(new ComboBox()));}finally{window.Close();} }),
        new("UiInput.RotatedResizeKeepsAnchor",()=>{var d=CommandCases.Scene();var b=d.Root["balloons"]![0]!.AsObject();b["transform"]!["rotation"]=37;var corners=HandleHitTest.BalloonCorners(b);var args=HandleHitTest.ResizeBalloon(b,2,20,10);var after=new ComicEditor.Core.Commands.CommandProcessor().Plan(d,[new("balloon.transform","X",args)]).After.Root["balloons"]![0]!.AsObject();var next=HandleHitTest.BalloonCorners(after);Assert.True(Math.Abs(corners[0].X-next[0].X)<.000001&&Math.Abs(corners[0].Y-next[0].Y)<.000001);}),
        new("UiInput.VertexModeCannotDragFrameBody",()=>{var vm=new EditorViewModel(CommandCases.Scene());vm.Select("panel","A");var hit=HandleHitTest.Find(vm,EditMode.Vertex,new(70,40),8);Assert.True(hit is null||hit.DragKind.ToString()=="Select","Vertex mode must not drag frame body");})
    ];
}
